In [1]:
import nltk
import pandas as pd
from sklearn.metrics import classification_report
import numpy as np

In [2]:
import flair

In [3]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/sundesh/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [4]:
sid.polarity_scores("In case you missed our previous email, can you please take a look at it?")

{'neg': 0.133, 'neu': 0.727, 'pos': 0.139, 'compound': 0.0258}

In [5]:
from textblob import TextBlob

In [6]:
df = pd.read_csv('./gold_dataset.csv')

In [7]:
df['scores'] = df['tweet'].apply(lambda review: sid.polarity_scores(review))

In [8]:
df['compound']  = df['scores'].apply(lambda score_dict: score_dict['compound'])

In [9]:
df['comp_score'] = df['compound'].apply(lambda c: 'POSITIVE' if c >=0 else 'NEGATIVE')

In [10]:
df['scores_text_blob'] = df['tweet'].apply(lambda review: TextBlob(review).sentiment.polarity)
df['comp_score_text_blob'] = df['scores_text_blob'].apply(lambda c: 'POSITIVE' if c >=0 else 'NEGATIVE')

In [ ]:
flair_sentiment = flair.models.TextClassifier.load('en-sentiment')
df['scores_flair'] = df['tweet'].apply(lambda review: flair_sentiment.predict(s).labels)
# df['comp_score_text_blob'] = df['scores_text_blob'].apply(lambda c: 'POSITIVE' if c >=0 else 'NEGATIVE')


2021-12-10 20:58:34,460 https://nlp.informatik.hu-berlin.de/resources/models/sentiment-curated-distilbert/sentiment-en-mix-distillbert_4.pt not found in cache, downloading to /tmp/tmphcu_cr_k


 21%|██        | 54639616/265512723 [05:38<1:01:16, 57352.43B/s]

In [22]:
df.head(5)

id           created_at  \
0  1369812663623180288   2021-03-11 6:19:23   
1  1354514776534220804   2021-01-28 1:11:03   
2  1349045265945264130  2021-01-12 22:57:10   
3  1366793773728980992  2021-03-02 22:23:24   
4  1371004616897269763  2021-03-14 13:15:47   

                                               tweet  sum true_value  \
0  In great news my senior parents are getting th...  2.0   POSITIVE   
1  Our Co-Founder and CEO <USER> recently receive...  2.0   POSITIVE   
2  "This is all we have left. This can't fail." <...  0.2   POSITIVE   
3  Dear #MAGA Trump NEVER cared about you. He Jim... -1.2   NEGATIVE   
4  I am all for risk triaging and in turn getting... -1.1   NEGATIVE   

  polarity_api_output  is_same  \
0            POSITIVE        1   
1            NEGATIVE        0   
2            POSITIVE        1   
3            POSITIVE        0   
4            POSITIVE        0   

                                  concept_api_output      conversation_id  \
0  ['great news', 'senior', 'vaccine', 'thank', '...  1369812663623180288   
1  ['founder', 'recent', 'covid', 'vaccine', 'vac...  1354514776534220804   
2  ['fail', 'make', 'vaccine', 'priority', 'plus'...  1349045265945264130   
3  ['cared', 'stop', 'punch', 'plane', 'traitor',...  1366793773728980992   
4  ['health care', 'risk', 'turn', 'vaccine', 'va...  1371004616897269763   

         date  ... reply_to  retweet_date  translate trans_src trans_dest  \
0  2021-03-11  ...       []           NaN        NaN       NaN        NaN   
1  2021-01-28  ...       []           NaN        NaN       NaN        NaN   
2  2021-01-12  ...       []           NaN        NaN       NaN        NaN   
3  2021-03-02  ...       []           NaN        NaN       NaN        NaN   
4  2021-03-14  ...       []           NaN        NaN       NaN        NaN   

                                              scores compound comp_score  \
0  {'neg': 0.0, 'neu': 0.575, 'pos': 0.425, 'comp...   0.8625   POSITIVE   
1  {'neg': 0.0, 'neu': 0.725, 'pos': 0.275, 'comp...   0.9230   POSITIVE   
2  {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...   0.0000   POSITIVE   
3  {'neg': 0.183, 'neu': 0.719, 'pos': 0.098, 'co...  -0.3013   NEGATIVE   
4  {'neg': 0.042, 'neu': 0.841, 'pos': 0.117, 'co...   0.5789   POSITIVE   

  scores_text_blob comp_score_text_blob  
0         0.800000             POSITIVE  
1         0.516667             POSITIVE  
2        -0.250000             NEGATIVE  
3         0.000000             POSITIVE  
4         0.291667             POSITIVE  

[5 rows x 46 columns]

In [23]:
y_true = df['true_value'].to_numpy()
y_pred_vader = df['comp_score'].to_numpy()
y_pred_sentic = df['polarity_api_output'].to_numpy()
y_pred_text_blob = df['comp_score_text_blob'].to_numpy()

In [32]:
def calc_label(y):
    x = y.copy()
    x[x=="POSITIVE"] = int(1)
    x[x=="NEGATIVE"] = int(-1)
    return x.astype('int64')

In [61]:
def calc_ensemble(y1, y2, y3):
    x1, x2, x3 = calc_label(y1), calc_label(y2), calc_label(y3)
    ans = np.zeros(y1.shape)
    
    ans[(x1+x2+x3)>=0] = 1
    ans[(x1+x2+x3)<0] = -1
    print(x1[:10])
    print(x2[:10])
    print(x3[:10])
    print(ans[:10])
    print(calc_label(y_true)[:10])
    return ans.astype('int64')

In [62]:
print(classification_report(calc_label(y_true), calc_label(y_pred_sentic)))

              precision    recall  f1-score   support

          -1       0.52      0.51      0.52       171
           1       0.75      0.76      0.75       329

    accuracy                           0.67       500
   macro avg       0.64      0.63      0.64       500
weighted avg       0.67      0.67      0.67       500



In [63]:
print(classification_report(calc_label(y_true), calc_label(y_pred_vader)))

              precision    recall  f1-score   support

          -1       0.85      0.51      0.64       171
           1       0.79      0.95      0.86       329

    accuracy                           0.80       500
   macro avg       0.82      0.73      0.75       500
weighted avg       0.81      0.80      0.79       500



In [64]:
print(classification_report(calc_label(y_true), calc_label(y_pred_text_blob)))

              precision    recall  f1-score   support

          -1       0.65      0.37      0.47       171
           1       0.73      0.89      0.81       329

    accuracy                           0.72       500
   macro avg       0.69      0.63      0.64       500
weighted avg       0.70      0.72      0.69       500



In [65]:
print(classification_report(calc_label(y_true), calc_ensemble(y_pred_sentic, y_pred_vader, y_pred_text_blob)))

[ 1 -1  1  1  1  1  1 -1  1  1]
[ 1  1  1 -1  1  1  1  1  1 -1]
[ 1  1 -1  1  1  1  1  1  1  1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  1  1 -1 -1  1 -1  1  1 -1]
              precision    recall  f1-score   support

          -1       0.84      0.42      0.56       171
           1       0.76      0.96      0.85       329

    accuracy                           0.77       500
   macro avg       0.80      0.69      0.70       500
weighted avg       0.79      0.77      0.75       500



In [1]:
from datasets import load_dataset

dataset = load_dataset("sentiment140")

Downloading:   0%|          | 0.00/1.54k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/739 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/81.4M [00:00<?, ?B/s]

KeyboardInterrupt: 

In [ ]:
dataset